In [1]:
#import dependencies
import pandas as pd
import datetime as dt

In [2]:
#load raw csv file

weather_df = pd.read_csv('./weather_data_2010_present.csv')
weather_df

,STATION,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,FMTM,PGTM,TAVG,TMAX,...,WT11,WT13,WT14,WT15,WT16,WT17,WT18,WT19,WT21,WT22
0,USW00094846,41.96017,-87.93164,204.8,2010-01-01,10.29,2359.0,2351.0,NaN,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,USW00094846,41.96017,-87.93164,204.8,2010-01-02,11.86,928.0,2206.0,NaN,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00094846,41.96017,-87.93164,204.8,2010-01-03,10.29,2114.0,1917.0,NaN,18.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
3,USW00094846,41.96017,-87.93164,204.8,2010-01-04,11.41,1644.0,1300.0,NaN,18.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
4,USW00094846,41.96017,-87.93164,204.8,2010-01-05,8.50,1518.0,1500.0,NaN,23.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4387,USW00094846,41.96017,-87.93164,204.8,2022-01-05,NaN,NaN,NaN,24.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4388,USW00094846,41.96017,-87.93164,204.8,2022-01-06,11.86,NaN,NaN,11.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,USW00094846,41.96017,-87.93164,204.8,2022-01-07,7.61,NaN,NaN,6.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,USW00094846,41.96017,-87.93164,204.8,2022-01-08,11.41,NaN,NaN,18.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,USW00094846,41.96017,-87.93164,204.8,2022-01-09,12.08,NaN,NaN,28.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#check all column header names
weather_df.columns

Index(['STATION', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'AWND', 'FMTM',
       'PGTM', 'TAVG', 'TMAX', 'TMIN', 'WDF2', 'WDF5', 'WSF2', 'WSF5', 'WT01',
       'WT02', 'WT03', 'WT04', 'WT05', 'WT06', 'WT07', 'WT08', 'WT09', 'WT11',
       'WT13', 'WT14', 'WT15', 'WT16', 'WT17', 'WT18', 'WT19', 'WT21', 'WT22'],
      dtype='object')

In [4]:
#rename columns
weather_df.rename({'STATION': 'Station',
                   'LATITUDE': 'Latitude',
                   'LONGITUDE': 'Longitude',
                   'ELEVATION': 'Elevation',
                   'DATE': 'Date',
                   'AWND': 'Average_Wind_Speed',
                   'FMTM': 'Time_of_Fastest_Wind',
                   'PGTM': 'Peak_Gust_Time',
                   'TAVG': 'Average_Temperature',
                   'TMAX': 'Maximum_Temperature',
                   'TMIN': 'Minimum_Temperature',
                   'WDF2': 'Direction_Fastest_2_Minute_Wind',
                   'WDF5': 'Direction_Fastest_5_Minute_Wind',
                   'WSF2': 'Fastest_2_Minute_Wind_Speed',
                   'WSF5': 'Fastest_5_Minute_Wind_Speed',
                   'WT01': 'Fog_Ice_Freezing_Fog',
                   'WT02': 'Heavy_Fog_or_Heavy_Freezing_Fog',
                   'WT03': 'Thunder',
                   'WT04': 'Ice_Pellets_Sleet_or_Small_Hail',
                   'WT05': 'Hail',
                   'WT06': 'Glaze_or_Rime',
                   'WT07': 'Dust_Volcanic_Ash_or_Blowing_Dust',
                   'WT08': 'Smoke_or_Haze',
                   'WT09': 'Blowing_or_Drifting_Snow',
                   'WT11': 'High_or_Damaging_Winds',
                   'WT13': 'Mist',
                   'WT14': 'Drizzle',
                   'WT15': 'Freezing_Drizzle',
                   'WT16': 'Rain',
                   'WT17': 'Freezing_Rain',
                   'WT18': 'Snow_Snow_Pellets_or_Ice Crystals',
                   'WT19': 'Unknown_Precipitation',
                   'WT21': 'Ground_Fog',
                   'WT22': 'Ice_fog_or_Freezing_Fog'
                  }, axis='columns', inplace=True)
weather_df

,Station,Latitude,Longitude,Elevation,Date,Average_Wind_Speed,Time_of_Fastest_Wind,Peak_Gust_Time,Average_Temperature,Maximum_Temperature,...,High_or_Damaging_Winds,Mist,Drizzle,Freezing_Drizzle,Rain,Freezing_Rain,Snow_Snow_Pellets_or_Ice Crystals,Unknown_Precipitation,Ground_Fog,Ice_fog_or_Freezing_Fog
0,USW00094846,41.96017,-87.93164,204.8,2010-01-01,10.29,2359.0,2351.0,NaN,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,USW00094846,41.96017,-87.93164,204.8,2010-01-02,11.86,928.0,2206.0,NaN,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00094846,41.96017,-87.93164,204.8,2010-01-03,10.29,2114.0,1917.0,NaN,18.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
3,USW00094846,41.96017,-87.93164,204.8,2010-01-04,11.41,1644.0,1300.0,NaN,18.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
4,USW00094846,41.96017,-87.93164,204.8,2010-01-05,8.50,1518.0,1500.0,NaN,23.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4387,USW00094846,41.96017,-87.93164,204.8,2022-01-05,NaN,NaN,NaN,24.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4388,USW00094846,41.96017,-87.93164,204.8,2022-01-06,11.86,NaN,NaN,11.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,USW00094846,41.96017,-87.93164,204.8,2022-01-07,7.61,NaN,NaN,6.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,USW00094846,41.96017,-87.93164,204.8,2022-01-08,11.41,NaN,NaN,18.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,USW00094846,41.96017,-87.93164,204.8,2022-01-09,12.08,NaN,NaN,28.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#set date column to datetime format
weather_df['Date'] = pd.to_datetime(weather_df['Date']).dt.date
weather_df

,Station,Latitude,Longitude,Elevation,Date,Average_Wind_Speed,Time_of_Fastest_Wind,Peak_Gust_Time,Average_Temperature,Maximum_Temperature,...,High_or_Damaging_Winds,Mist,Drizzle,Freezing_Drizzle,Rain,Freezing_Rain,Snow_Snow_Pellets_or_Ice Crystals,Unknown_Precipitation,Ground_Fog,Ice_fog_or_Freezing_Fog
0,USW00094846,41.96017,-87.93164,204.8,2010-01-01,10.29,2359.0,2351.0,NaN,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,USW00094846,41.96017,-87.93164,204.8,2010-01-02,11.86,928.0,2206.0,NaN,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00094846,41.96017,-87.93164,204.8,2010-01-03,10.29,2114.0,1917.0,NaN,18.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
3,USW00094846,41.96017,-87.93164,204.8,2010-01-04,11.41,1644.0,1300.0,NaN,18.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
4,USW00094846,41.96017,-87.93164,204.8,2010-01-05,8.50,1518.0,1500.0,NaN,23.0,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4387,USW00094846,41.96017,-87.93164,204.8,2022-01-05,NaN,NaN,NaN,24.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4388,USW00094846,41.96017,-87.93164,204.8,2022-01-06,11.86,NaN,NaN,11.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4389,USW00094846,41.96017,-87.93164,204.8,2022-01-07,7.61,NaN,NaN,6.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4390,USW00094846,41.96017,-87.93164,204.8,2022-01-08,11.41,NaN,NaN,18.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4391,USW00094846,41.96017,-87.93164,204.8,2022-01-09,12.08,NaN,NaN,28.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
weather_df.count()

Station                              4392
Latitude                             4392
Longitude                            4392
Elevation                            4392
Date                                 4392
Average_Wind_Speed                   4386
Time_of_Fastest_Wind                  638
Peak_Gust_Time                        634
Average_Temperature                  3206
Maximum_Temperature                  4391
Minimum_Temperature                  4391
Direction_Fastest_2_Minute_Wind      4386
Direction_Fastest_5_Minute_Wind      4370
Fastest_2_Minute_Wind_Speed          4386
Fastest_5_Minute_Wind_Speed          4370
Fog_Ice_Freezing_Fog                 1585
Heavy_Fog_or_Heavy_Freezing_Fog       121
Thunder                               481
Ice_Pellets_Sleet_or_Small_Hail        53
Hail                                  113
Glaze_or_Rime                          48
Dust_Volcanic_Ash_or_Blowing_Dust      20
Smoke_or_Haze                         783
Blowing_or_Drifting_Snow               49
High_or_Damaging_Winds                  9
Mist                                  369
Drizzle                                78
Freezing_Drizzle                        4
Rain                                  466
Freezing_Rain                           5
Snow_Snow_Pellets_or_Ice Crystals     195
Unknown_Precipitation                   1
Ground_Fog                              3
Ice_fog_or_Freezing_Fog                18
dtype: int64

In [7]:
#Drop unneeded columns
weather_df = weather_df.drop(columns=[
    'Station',
    'Latitude',
    'Longitude',
    'Elevation',
    'Time_of_Fastest_Wind',
    'Peak_Gust_Time',
    'Direction_Fastest_2_Minute_Wind',
    'Direction_Fastest_5_Minute_Wind',
    'Fastest_2_Minute_Wind_Speed',
    'Fastest_5_Minute_Wind_Speed',
    'Ice_Pellets_Sleet_or_Small_Hail',
    'Glaze_or_Rime',
    'Dust_Volcanic_Ash_or_Blowing_Dust',
    'Blowing_or_Drifting_Snow',
    'High_or_Damaging_Winds',
    'Drizzle',
    'Freezing_Drizzle',
    'Unknown_Precipitation',
    'Ground_Fog',
    'Ice_fog_or_Freezing_Fog'   
])
weather_df.head()

,Date,Average_Wind_Speed,Average_Temperature,Maximum_Temperature,Minimum_Temperature,Fog_Ice_Freezing_Fog,Heavy_Fog_or_Heavy_Freezing_Fog,Thunder,Hail,Smoke_or_Haze,Mist,Rain,Freezing_Rain,Snow_Snow_Pellets_or_Ice Crystals
0,2010-01-01,10.29,NaN,16.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,2010-01-02,11.86,NaN,11.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-03,10.29,NaN,18.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
3,2010-01-04,11.41,NaN,18.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0
4,2010-01-05,8.50,NaN,23.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0

In [8]:
#export to csv
output_data_file = "clean_weather_data.csv"
weather_df.to_csv(output_data_file, index=False)

In [10]:
#connect to postgresSQL and movies_df DataFrame to SQL Database
from config import db_password
from sqlalchemy import create_engine
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/chicago_crime"
engine = create_engine(db_string)
weather_df.to_sql(name='weather_data', con=engine)